### ISSUE TITLE
WebClientAdapter.js missing?

### ISSUE THREAD

**Issue by jwulf** [salboaie/SwarmESB#7]
I followed the installation instructions here: https://github.com/salboaie/SwarmESB/wiki/Install-guide

When I run  [~/workspace/SwarmESB] $ node adapters/Launcher.js, I get:

[24-5,0:48][Launcher] WebClientAdapter need restart[6].Not alive.
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/sitapati/workspace/SwarmESB/adapters/WebClientAdapter.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by salboaie** [comment]
Could you check SwarmCore project and https://github.com/salboaie/WSSwarmClient ? I plan to keep SwarmESB as the main repository for documentations and exmaple of how to use Swarm. Currently I work to a refactred version of SwarmESB and many good thins stays in SwarmCore.

**Comment by jwulf** [comment]
OK, I have checked out SwarmCore and started using that to develop my application. I'm writing a book as I go:  https://github.com/jwulf/SwarmCoreByExample/blob/master/1.adoc

**Comment by salboaie** [comment]
Thank you very much!!! I will check the book when is ready!
