### ISSUE TITLE
Launcher will not die

### ISSUE THREAD

**Issue by jwulf** [salboaie/SwarmESB#8]
I cannot kill the launcher. When I hit ^C I get the following:

^C[24-5,0:54][Launcher] Got SIGINT.
Retrying swarm propagation towards SwarmCoreExample:Logger: {"meta":{"name":"log.js","swarmingName":"log.js","currentPhase":"doLog","command":"phase","swarmCounter":"Launcher:263"},"message":"Got SIGINT.","level":"ERROR","userId":null,"debug":"false","nodeName":"Launcher","stack":""}
Retrying swarm propagation towards SwarmCoreExample:Logger: {"meta":{"name":"log.js","swarmingName":"log.js","currentPhase":"doLog","command":"phase","swarmCounter":"Launcher:264","timout":1000},"message":"Got SIGINT.","level":"ERROR","userId":null,"debug":"false","nodeName":"Launcher","stack":""}

**Comment by jwulf** [comment]
The only way I can stop it is to get the PID and issue kill -9

**Comment by salboaie** [comment]
the launcher in SwarmCore is much better and stable.
